name: Bug Report
description: Report an issue with RiseOfTheRoninFix
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "## Please fill out the details below."

  - type: input
    id: version
    attributes:
      label: "Version Number"
      description: "Which version of RiseOfTheRoninFix are you using? (Check the release name or `RiseOfTheRoninFix.log`)"
      placeholder: "e.g., v0.0.1"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "Describe the Issue"
      description: "What happened? Provide a clear and concise description of the bug."
      placeholder: "Example: The game crashes when entering a specific area..."
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "How can the issue be reproduced? Provide step-by-step instructions."
      placeholder: |
        1. Launch the game
        2. Load a specific save
        3. Trigger the issue
        4. Observe the bug
    validations:
      required: true

  - type: textarea
    id: log-file
    attributes:
      label: "Log File"
      description: "Please upload `RiseOfTheRoninFix.log` from the game folder."
    validations:
      required: true
